language: ruby
rvm:
- 2.2

#env:
#  global:

deploy:
  provider: s3 
  bucket: quantum-sprinkles
  skip_cleanup: true
  access_key_id:
    secure: CgHeUj2KKj4b9ADPoDlIaCA9HNqQKXg1sC0tHKz2rKuPSFiya2+ibLOLt8VJ0/Zyig97Ns3cEFgFM5RGITa0FrpQ3gksMMi+5aEgfWNYHCjyQkG49Q/+05jgso2nttVONBztLZXVP2RZXI6kkA8ci9Ks+AkkofVuZzdW+mEMA/M7Si0uEp3rC4oI8CDAOwhxgyfn3RYdl3VotIvYYl4irM3E3M6JMfXSbHr/6tUMHi+UMBif1KKwY0ggesreaKcVnsYYM4/IrtSPwOlWljV5Hji2TP0bfxG02mDlvNrpdjsAtv8v5dRFlmthJkFNlBX203rgU/AkrMc4j4cEw9ZXLzP20Ydtmfffd+kqMVtR7kNdgapItDFBLzK5+bowfrGLE/GMY/Br7w8/NW5MOYolu9hagESuYBi9H4GqeDn68ymE1+BMJZFQ18ck90K4nd5BrIb5ElU3xLR3ZgqTkqmVH325X6s3X5Ci8OeBINQjaHhz8VA0J5msGYoG+gNb5P2GoGEmqzfRJAlIMybDvQn+PotMCHxrrHI/oagapHWAe0l/d1rXa7iRy0Vij2vlkEefP2ookLhTOz7QUtCxjMj9IWDAaSrImdImEhBgI1MRKGQTJ9KkVaTq7BRa5Hxw9q0p0wCegCN6p1RqwTmReIAa0BgHF6mc/SzNruiXnAiSSkQ=
  secret_access_key:
    secure: WBmF6dJYMOpgBgwawAp1nxdMS/K/Weq4wvGljCLlecIVO0Gs5sO3/sGeyQE+oUEeEJyAmVxbZ6EnePwqbUKOnXzXl/WSuDToXfHRzChYxkoxF5HctIroAhie3vKTy4qSjz+aWTgCPznLaZy4SoWk9jXABV95UqCa2h5b7QXgSH6B6Ko2E9zpy1HppKdVqciYC7ckSTHFGdU/5KjdB04EXxxeJlqY7ryV1vUqcQoRoKeIFOomQphS2XAreYhfwwLXpHOOQVbkxr8tg6O840KnEIRwmlwRXmH93n4D0p7ZQTDIjXxTfV1hOpTYrp4Ys1AiTcJqwLuWgqwQGep21euH0KWxKNCVMZNam1kXE6V8egp0VuoeECcgbZZsbehnRtnBzpJ93FQ86xQ8kJz04FgfaZOmOJLNiZnv2acBpe9LEuO+Zr9w+KEgYY3eLFUwIaw2zOf2MM+Fp3WlDx/NOqmwi9j6HOqcDjErlKr7ePnDYJZ3Q1dUNQXJDorCpxg3iyxOjzv2LsIlk5PtbdxP4mGawjGtIRX6huFMG7r6r4jcGG/n368IIXq77p+Q9BkDOK+Uz7oeTvfnGGfUhKuQ2P7BFZ5mnVmtivuByWDCiuBogbakOpjV2Hhf/o2oaD4+RWxsLkkOIrxL3wQl5G5cR/CVmnRcRt6cIIwL8lQNxmI01Yo=


