#!/bin/bash
# Quantum Sprinkles
# /etc/init.d Control Script

# This started life as GemInABox - https://gist.github.com/davidhooey/5454747

### BEGIN INIT INFO
# Provides:          quantum-sprinkles
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Ruby rackup control script for Quantum Sprinkles
### END INIT INFO

USERNAME="ec2-user"
HOME_DIR="/home/ec2-user"
APP_ROOT="$HOME_DIR/app"
RACK_PID="$APP_ROOT/rack.pid"
RACK_UP="$HOME_DIR/bin/rackup -o 0.0.0.0 -E Production -D -P $RACK_PID"
NAME="rack"
DESC="Quantum Sprinkles Service"

get_api_key(){
    echo "ENTER THE JAZZ API ACCESS KEY"
    read APIKEY
}

check_pid(){
    if [ -f $RACK_PID ]; then
        PID=`cat $RACK_PID`
        STATUS=`ps aux | grep $PID | grep -v grep | wc -l`
    else
        STATUS=0
        PID=0
    fi
}

start() {
    cd $APP_ROOT
    check_pid
    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
        # Program is running, exit with error code 1.
        echo "Error! $DESC $NAME is currently running!"
        exit 1
    else
        if [ `whoami` = root ]; then
            get_api_key
            sudo -u $USERNAME -H bash -l -c "export JAZZ_KEY=$APIKEY ; $RACK_UP"
            echo "$DESC started"
        else
            echo "Error! This script was intended to be run using sudo."
            exit 1
        fi
    fi
}

stop() {
    cd $APP_ROOT
    check_pid
    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
        ## Program is running, stop it.
        kill -QUIT `cat $RACK_PID`
        echo "$DESC stopped"
	sleep 1
        if [ -f $RACK_PID ]; then
          rm "$RACK_PID" >> /dev/null
        fi
    else
        ## Program is not running, exit with error.
        echo "Error! $DESC not started!"
        exit 1
    fi
}

status() {
    cd $APP_ROOT
    check_pid
    if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
        echo "$DESC with PID $PID is running."
    else
        echo "$DESC is not running."
        exit 1
    fi
}

## Check to see if we are running as root first.
## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
fi

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: sudo service quantum-sprinkles {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
